### PR TITLE
Julian/hover states

### PR DESCRIPTION
**Pull request by julianbauer**
Hover and focussed states for primary and secondary buttons

### CODE REVIEW

**Review by danimoh — APPROVED** [review]
Looks good

**Comment by sisou** [comment]
The buttons are very blurred for me during hover states. It's particularly visible in the small buttons:
Non-Hover:
screenshot from 2018-12-19 14-41-23

During hover:
screenshot from 2018-12-19 14-39-30

I don't think this looks good. I think we should either remove scaling from hover effects, or make it so that it grows a whole pixel instead of just half of one. But I don't think thats possible to generalize for different button sizes. Thus I think scaling is out-of-the-question.

**Comment by danimoh** [comment]
That's true unfortunately it gets a bit blurry.
I tried with your previous version, the version where I removed the `will-change: transform` and your newest version. Unfortunately it looks about the same in all versions.

The issue is most noticable for the small button. For the colored buttons it's about not noticable.

**Comment by julianbauer** [comment]
I think so too – with the `perspective` fix, the big button works well, the small button still is blurry, and the small link also doesn't perform very well. We're exploring how to solve it right now

**Pull request merged**
